### ISSUE TITLE
Incorrect delta_t and time in GKOutputReaderGENE.py

### ISSUE THREAD

**Issue by ajaycj1** [bpatel2107/pyrokinetics#100]
https://github.com/pyro-kinetics/pyrokinetics/blob/1f31a6e9e3ca2c739a8dc5ad110405772df696ed/pyrokinetics/gk_code/GKOutputReaderGENE.py#L113
This is the time taken by the machine to compute one step and not the delta_t in simulation. 
The following line `time = np.linspace(0, delta_t * (ntime - 1), ntime)` is also therefore incorrect.
`time` is correctly overwritten in _set_fields, but this correction does not happen when field file cannot be read.

**Comment by bpatel2107** [comment]
Is there a place where time can be read in before the fields are read in?

**Comment by ajaycj1** [comment]
Time can be read in fields, nrg or mom files. So, in the current version of GKOutputReaderGENE.py, I suggest that it should be read from nrg file if fields file is unreadable, and if nrg file is unreadable as well, time should remain empty. 

A general question: There are a few similar changes in this file, which I have made in my branch. Also included the ability to read field.h5 files. Should I raise an issue for each of these changes or just make a pull request after everything is done?

**Comment by bpatel2107** [comment]
My only concern is reading in the fields file which can be quite large. I think the nrg file is much smaller so that might be the best place to start and only open the fields file as a last resort.

Smaller PRs are always nicer, especially if they are relatively stand alone
