### ISSUE TITLE
Test failure + question on PRs

### ISSUE THREAD

**Issue by ajaycj1** [bpatel2107/pyrokinetics#105]
Hi @bpatel2107,

So far Pyrokinetics was not reading the last time step entry in field and nrg output files. It used to read only up to the second last entry. I corrected this. 
However the tests are not updated to account for this, hence the check failures in my pull request. 
It feels a bit weird for me to correct the test outputs and then make my changes pass it, so can you correct them, or should I do it as well?

I also made new changes to account for circular ad-hoc geometry. Shall I push them to my branch? I am asking because you said smaller pull requests are preferred and I don't want to compound everything together.

**Comment by bpatel2107** [comment]
I think you should update the test outputs too so it a complete PR, otherwise there are a bunch of unnecessary PRs.

The circular ad-hoc geometry sounds like a separate PR to me. There's not really an issue having a lot of PRs, as long as they address different issues

**Comment by ajaycj1** [comment]
Sorry, I don't know the git technicalities in detail. As I understand, if I push to my branch now, the existing pull request will be updated to account for the new (circular geometry) changes as well. So should I create a new branch for a new pull request (which is a bit less preferred)?

**Comment by bpatel2107** [comment]
So you should make a new branch based off your master branch. Make changes in there and then make a new PR based off of that branch.

If you merge one after the other then git will handle any merging issues it can and where there are conflicts it will ask you to fix them.

Another option is once one of the PRs is accepted, you merge the updated master branch into your second PR's branch and handle the merge conflicts there
