### ISSUE TITLE
Definition of rho

### ISSUE THREAD

**Issue by ajaycj1** [bpatel2107/pyrokinetics#106]
Is rho =  minor_r (as defined in GKInputGENE.py for miller) or is it equal to trpeps?
trpeps=r/R is the inverse aspect ratio of the fluxtube centered at r.

**Comment by bpatel2107** [comment]
rho is minor_r
https://pyrokinetics.readthedocs.io/en/latest/rst_docs/miller.html

**Comment by ajaycj1** [comment]
Thanks. 
rho=r/a. What is r here? I would assume it is the radius of the local flux-surface being considered.
In GENE I think minor_r is the minor radius of the device and not of the local flux-surface being considered.

**Comment by bpatel2107** [comment]
I haven't implemented GENE here 

@dake0795 did before the refactor and it looks like he set `treps` correctly.

https://github.com/pyro-kinetics/pyrokinetics/blob/db7b4cb10ac69bfdbfff42f84f4ec0245123e2e4/pyrokinetics/gk_code/GKCodeGENE.py#L144

It looks like we should have  `minor_r=1.0` and `treps=miller.rho/miller.Rmaj`

Can you confirm this?

**Comment by ajaycj1** [comment]
If trpeps=miller.rho/miller.Rmaj, then miller.rho is the normalised radius of the flux-tube being considered. In that case, rho=minor_r would not be correct for GENE. 
I don't have much experience with geometry related stuff, so maybe better if someone else look into this.

**Comment by bpatel2107** [comment]
@dake0795 thoughts?

**Comment by bpatel2107** [comment]
I'm pretty confident this is an error. We need to redefine `miller.rho` from `miller.Rmaj` and `trpeps` and set `minor_r=1.0`, will have to open a PR for this

**Comment by dake0795** [comment]
@bpatel2107 yep, looks like an error. Your suggested fix is correct, I think we should define `miller.rho = trpeps * major_R`. minor_r=1.0 for Miller. 

@ajaycj1  thanks for the spot. Good to have another GENE user looking at this.

**Comment by bpatel2107** [comment]
Fixed in #110
