### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by ZedThree** [bpatel2107/pyrokinetics#111]
We've not had a release in about a year, and there have been quite a few changes since then: bugfixes, features, refactoring, etc.
@bpatel2107 Is it ok if I make a new release, v0.3.0?

We should probably try to make more frequent releases, which will help make sure people are using the latest version. We've automated the publishing using Github releases, so it's very low effort to make a new release. Github can now also auto-generate the changelog, which is nice. Maybe every month, assuming there have actually been any changes?

**Comment by bpatel2107** [comment]
Yeah that seems reasonable. I was waiting for the refactor and then it slipped off my radar. Happy for once a month or so.

**Comment by ZedThree** [comment]
v0.3.0 here: https://github.com/pyro-kinetics/pyrokinetics/releases/tag/v0.3.0

**Comment by bpatel2107** [comment]
Will need to re-learn how to do this!
