### ISSUE TITLE
Pint attribute name using . or -

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#130]
Currently pyro attempts to name a normalisation convention based off of the input files such as `kinetics_file` or `eq_file`.

However if that file happens to have a '.' or '-' or '+' or any other python operation (e.g. `my-profiles.cdf`) then Pint throws up an error here

https://github.com/pyro-kinetics/pyrokinetics/blob/8542764dadca18065390184b39cecc8d605ef033/pyrokinetics/normalisation.py#L509-L520

Essentially it will try and evaluate that operation in the `getattr` and throw up an error

Easiest fix is to change the `self.name` when initially defined here to just `run` 
https://github.com/pyro-kinetics/pyrokinetics/blob/8542764dadca18065390184b39cecc8d605ef033/pyrokinetics/pyro.py#L87-L89
https://github.com/pyro-kinetics/pyrokinetics/blob/8542764dadca18065390184b39cecc8d605ef033/pyrokinetics/pyro.py#L164-L172

@ZedThree Is there a fancy way to remove these kind of strings from name automatically?

**Comment by ZedThree** [comment]
This SO answer has a method for sanitising identifier names: https://stackoverflow.com/a/10121078

**Comment by bpatel2107** [comment]
Fixed in #131
