### ISSUE TITLE
Density/temperature not normalised correctly 

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#132]
When running the example scripts `example_JETTO.py` and `example_TRANSP.py` the density and temperature are not being normalised correctly.

For example in the output of `example_JETTO.py` in `test_jetto.gs2` the electron density is written as 

```
    z = -1
    dens = 6.959310030892369e+20
    temp = 0.49999999999999994
```

Where both `dens` and `temp` should be 1.0

@ZedThree thoughts?

**Comment by bpatel2107** [comment]
Note the mass, gradients and collisionality look correct.

**Comment by ZedThree** [comment]
Something's changed in the normalisations, and the reference units are getting converted to the "wrong" base units -- for example, density is getting converted to `1 / lref**3`.

I'm not sure why that's happening now, as I thought this was working correctly previously

**Comment by bpatel2107** [comment]
Yeah this is what I had suspected but I have no idea why? I'm really not familiar with pint yet. Is it a version issue with pint?
