### ISSUE TITLE
CGYRO heat flux with flow shear

### ISSUE THREAD

**Issue by mgiacomin** [bpatel2107/pyrokinetics#152]
https://github.com/pyro-kinetics/pyrokinetics/blob/3d083304a212d2db1f873f261cd4ee585b0764dc/pyrokinetics/gk_code/GKOutputReaderCGYRO.py#L318-L321
Why is `cflux` loaded in place of `gflux` in CGYRO simulations with flow shear? According to the CGYRO documentation
```
gflux(0,ky) = Domain-averaged flux [this is the standard flux-tube flux]
cflux(ky) = Interior-averaged flux [this is the "central" flux]
```
we should always consider gflux, which is the standard flux-tube flux.  `cflux` includes only the average flux in the "positive-shear region".
@bpatel2107 What do you think?

**Comment by bpatel2107** [comment]
This is what is done in the GACODE plotting scripts so I matched accordingly.

https://github.com/gafusion/gacode/blob/4971325b1e6ce786356cfca95d9da5848377e48a/f2py/pygacode/cgyro/data.py#L135-L145

There's also this note
```
! NOTE:
!  cflux is only of interest when profile or ExB shear is active
!  cflux(ky) is the average flux in the "positive-shear region"
!  gflux(ky,0)-cflux is the flux in the "negative-shear region"
```

So I guess cflux is the average flux on the outward side of the flux tube. I agree that we may want to use the same definition throughout. Need to see what GENE/GS2 do when there is flow shear.

**Comment by d7919** [comment]
I'm not aware of GS2 doing anything differently in the diagnostics for runs with flow shear.
My preference would be for us to plot the same quantity in runs with and without flow shear, whilst perhaps flagging to the user that there's another option for CGYRO.

**Comment by mgiacomin** [comment]
I don't think that a different definition of heat flux is used in GENE in presence of flow shear (at least from the documentation), but I haven't look into the source code. 
@dake0795 Are you aware of a different heat flux in GENE when `ExBrate` $\ne 0$?

**Comment by dake0795** [comment]
There is definitely no other definition of the heat flux in GENE. This seems very strange!

**Comment by mgiacomin** [comment]
The numerical implementation of flow shear in CGYRO when `SHEAR_METHOD=2` leads to a different definition of fluxes, in particular for the momentum flux. The heat flux doesn't change a lot between `gflux` and `cflux` and I prefer `gflux` since it is what we have in GS2 and GENE. However, momentum flux will be off if `gflux` is used with `SHEAR_METHOD=2`.  I will try to implement something on this way.

**Comment by bpatel2107** [comment]
I think I agree that cross-code consistency is the most important thing. Happy to switch to `gflux` for now
