### ISSUE TITLE
Flipping psi_RZ grid doesn't flip q

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#159]
Currently pyro forces `psi` to increase from the magnetic axis to the last closed flux surface. It flips the sign the `psi` along with derivatives w.r.t `psi`

https://github.com/pyro-kinetics/pyrokinetics/blob/ca344686b2ab4bc08d07a79c23ea96f33b7d170e/pyrokinetics/equilibrium/geqdsk.py#L83-L91

Should the sign of `q` also be changed here?

I think this is basically an issue with the COCOs not being handled properly here, referencing #124 here

**Comment by LiamPattinson** [comment]
According to the COCOS document in the issue you linked, I think the answer depends on exactly which code produced the G-EQDSK file. It may also be necessary to adjust $f$ in some cases.

It might be possible to resolve all possible COCOS conventions using `omas.identify_cocos` and `omas.cocos_transform`. I'll have a play around with it and see if I can get something working.

**Comment by bpatel2107** [comment]
I think changing the sign of `psi` does complicate things. 

We can determine whether or not `\psi` is increasing or decreasing and the sign of `q` without problem. That immediately narrow its down to one of 2 COCOS (4 if you count the `n/10+n` ones). I don't think a GEQDSK file has any idea about whether `phi` is clockwise from above or not. So we are somewhat limited 

As a side note, I believe that you can arbitrarily add any value to `psi` without changing the equilibrium. As a pyrokinetics convention maybe we can shift the `psi` such that it is zero on axis.

**Comment by bpatel2107** [comment]
https://w3.pppl.gov/ntcc/TORAY/G_EQDSK.pdf

May have spoken too soon. In the GEQDSK manual apparently you're supposed to have a right handed (R, φ, Z) grid, meaning φ is counter-clockwise from above.

**Comment by LiamPattinson** [comment]
I don't know how well people actually stick to those standards, as it also states $\psi$ should be in webers per radian, but I'm pretty sure I came across an instance somewhere where it was just in webers and was out by a factor of $2\pi$ (though I forget where exactly).  

So far not having any luck with OMAS, as `identify_cocos` seems to be bugged. I'll see if I can reimplement some of it and get things working. I'll submit a PR to OMAS if I figure it all out.
