### ISSUE TITLE
Add in P-File reader for Kinetics 

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#166]
Osbourne P-files are another reasonably common profile data that we could use to load the kinetics object.

There seems to be an existing Pfile reader here:
https://github.com/PSFCPlasmaTools/eqtools

https://github.com/PSFCPlasmaTools/eqtools/blob/master/eqtools/pfilereader.py

and we can pip install the module.

So it would be reasonably straightforward to get the data out and into a format that pyrokinetics could handle.

We would need a P file template to test but seems pretty straightforward

**Comment by bpatel2107** [comment]
@jfparisi FYI

**Comment by jfparisi** [comment]
eqtools doesn't work as https://github.com/PSFCPlasmaTools/eqtools/blob/master/eqtools/pfilereader.py only works for python2.

For now, I imported OMFIT and added pFile read-in capability. I have only used OMFIT classes, which are available with pip:

pip install --upgrade omfit_classes

**Comment by bpatel2107** [comment]
The licence in eqtools allows for copying over so you can just take that and modify it to work in python3

**Comment by bpatel2107** [comment]
It actually looks like that code has been recently ported to python 3 so I think they haven't released a new version. We can make a issue to create a new version, though there hasn't been a commit in 3 years...

**Comment by bpatel2107** [comment]
Well looks like `eqtools` managed to release a new version of the code on pip so we can switch over to that if need be.

**Comment by LiamPattinson** [comment]
It looks like eqtools also handles geqdsk files, so if we end up bringing that in as a dependency we may not need freeqdsk. However, it looks like eqtools isn't on conda-forge, which will affect our own ability to host Pyrokinetics on conda (Issue https://github.com/pyro-kinetics/pyrokinetics/issues/170). It also uses `numpy.distutils` to handle F2PY Fortran bits, and this will not be supported by Python 3.12, planned for release in October this year. These are both totally fixable issues, but they'll require some extra work on the eqtools end.

**Comment by bpatel2107** [comment]
We can add in OMFIT as a dependency but that has quite strict limitations on modules at the moment so that may make the build even more complicated.

**Comment by bpatel2107** [comment]
Alternatively we could a P-file and A-file readers to FreeQDSK

**Comment by LiamPattinson** [comment]
I'm a little confused by the terminology. Are A-files and P-files the same as A-EQDSK and P-EQDSK? FreeQDSK can currently handle A-EQDSK but not P-EQDSK. I'm working over the docs for it now and getting a bit more familiar with how it all works, so that's definitely something we could add if I'm understanding correctly.

**Comment by bpatel2107** [comment]
I though that they were the same but maybe not... I found this website that has several different file formats

With "pfile"  standing for the Osbourne P file 
https://farside.ph.utexas.edu/EPEC-documentation/html/index.html#pfile-format

An in the same page they have "gfile" which is a GEQDSK format. Not sure if there is an official list of EQDSK types.
