### ISSUE TITLE
Flux surface fitting reader with fix boundary equilibrium

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#17]
Certain fix boundary codes like JETTO/SCENE may have EQDSK writers that set `psi = 0` outside the LCFS

This can lead to an issue when finding the last closed surfaced as done here 

https://github.com/pyro-kinetics/pyrokinetics/blob/3eb5452103d8f70fa32c5e94a684d72d63b93e3a/pyrokinetics/equilibrium.py#L112

https://github.com/pyro-kinetics/pyrokinetics/blob/3eb5452103d8f70fa32c5e94a684d72d63b93e3a/pyrokinetics/equilibrium.py#L141-L143

I have a JETTO run where finding the `psi_n=0.9999` surface is fine but no flux surface is found when `psi_n=1.0` 

Is it worth modifying the code such that `psi_n = linspace(0.0, 0.9999, self.nr)` instead?

**Comment by ZedThree** [comment]
`linspace` takes an `endpoint` argument that determines whether or not the last point is included, so if the issue is at exactly `psi_n == 1.0` and not inside that, then `linspace(0.0, 1.0, self.nr, endpoint=False)` is probably the better fix

**Comment by bpatel2107** [comment]
The only reason I suggest the 0.9999 is that I use the final flux surface to get the minor radius and set the LCFS.

https://github.com/pyro-kinetics/pyrokinetics/blob/3eb5452103d8f70fa32c5e94a684d72d63b93e3a/pyrokinetics/equilibrium.py#L141-L151

**Comment by ZedThree** [comment]
Ah ok, 0.9999 does have some significance! With my suggestion, the LCFS would be set at `1.0 - 1/self.nr` which sounds like it's not what you want.

In that case, as a magic number it should definitely have a name (maybe `psi_lcfs`?) and possibly be an input option?

**Comment by bpatel2107** [comment]
Fixed in #22
