### ISSUE TITLE
Change value_fmt=".3f" in PyroScan object : issue in CGYRO with directory name

### ISSUE THREAD

**Issue by juanruizruiz** [bpatel2107/pyrokinetics#197]
Following example in 

/unstable/pyrokinetics/examples/example_JETTO_1dscan.py

line 42 says 

pyro_scan = PyroScan(...) 

has an option value_fmt=".3f". This makes the output of lines 54 and 58 to write directories with a '.' in the directory, eg. 'ky_0.600' if doing a scan in ky. This by itself is not problematic. However, when attempting to submit the file for running CGYRO (perhaps other codes as well), the '.' in the directory name makes CGYRO complain. I suggest changing the value_fmt to something else without a '.', for creating directories eg. 'ky_0600' instead of 'ky_0.600'. Just a suggestion. This would be highly useful for those wanting to use PyroScan and submitting CGYRO jobs.

**Comment by d7919** [comment]
The '.' should be valid in a directory name, so I would lean towards this being something which should be fixed in the CGYRO handling. What is the problem that arises (e.g. what is the complaint)?

**Comment by bpatel2107** [comment]
I usually get around this by changing to that directory in python and then submitting. So I will copy my submit script to each directory, go into that directory and the submit from inside there.

My submit script will have the following:
`cgyro -e . -n <MPI> -nomp  <OMP>`

**Comment by juanruizruiz** [comment]
thanks for this last comment, having the batch submit file in the simulation directory got rid of the issue.
