### ISSUE TITLE
Choice of simulation files loaded in pyro.load_gk_output()

### ISSUE THREAD

**Issue by juanruizruiz** [bpatel2107/pyrokinetics#199]
The largest files in a NL GK simulation output are generally the moments (delta n, delta v, ..) and fields (delta phi, delta A_par, ...). Currently the command ' pyro.load_gk_output() ' loads fluxes and fields (moments are not implemented yet in pyro). The fields files are large and can take a significant time to load (minutes for large-ish sims). Sometimes one is not interested in reading the fields but would only want information about the fluxes for a quick check. It would be very convenient if one could specify in the command ' pyro.load_gk_output() ' whether one would like to read the fields (and moments in the future) or not. 

Beyond this is the issue of memory for large simulations when one is interested in reading the large fields and moments files. As an example, I recently ran a case on Marconi whose fields files were 18GB each. I was not able to read the files from the login nodes on Marconi, and I couldn't read the files from an interactive node either. I had to submit a batch file with 4 nodes for 20min to Marconi (specifying python routines using pyro) for pyro to read and load the files and generate the plots from the simulation. Is there a better way around that? I understand that the memory issue for large sim outputs will be there regardless of using pyro or not. One potential option that might be difficult to implement in pyro, but I wanted to suggest it : sometimes one is not interested in all the data in (kx, ky, theta, t), but perhaps only in a specific theta, ky or time. I do not know how difficult it would be to specify in ' pyro.load_gk_output() ' to load only a specific value of a variable or interest, say theta=0 or ky=0. This would greatly reduce the amount of data loaded in pyro and could easily resolve this memory issue.

**Comment by d7919** [comment]
I thought xarray supported lazy loading, so maybe pyro is forcing the data
to be loaded into memory prematurely (i.e. before we actually want it). I
guess for non-netcdf files we don't automatically get the same
functionality.

**Comment by mgiacomin** [comment]
@d7919 currently `pyro` loads all data related to fields and fluxes in order to populate the `xarray`. I think this is done to standardize the data reading from different (also non-netcdf) files.

**Comment by bpatel2107** [comment]
It is possible and in theory straight forward to select which bits of data get stored in `gk_output`.

The long part is usually the loading of data into memory. As @d7919 says, xarray lazily loads data, so when we have netCDF/HDf5 output then xarray can do this very quickly as we don't actually load the data into memory until it is requested.

The main issue is when we don't have netCDF outputs (GENE by default and CGYRO always) then we have to manually read in the data which is the thing that takes a long time. Unless we write a fancy way of reading the binary files where we can skip bits of data. I don't see any really chance of of selecting out a theta/time slice with ease though.

The easiest thing right now would be to select which fields/moments get loaded (fluxes tend to be small). Then we wouldn't load everything. This should be easy to do

**Comment by d7919** [comment]
One very hacky way would be to write something which constructs a netcdf file from the binary/text files. Whilst this does require us to read everything in we could then cache the netcdf file so subsequent analysis is faster. It should be possible to incrementally read in the source files and flush to disk to at least reduce peak memory requirements. This is likely to be pretty flaky and the suggestion of @bpatel2107 to enable simply reading the data which is needed is more sensible as a first step. One _could_ imagine actually defining a pyrokinetics storage format which we could convert raw data into.

**Comment by LiamPattinson** [comment]
Once PR https://github.com/pyro-kinetics/pyrokinetics/pull/182 is merged, we'll have issues with lazy-loading large files even when reading netCDF. We're using pint-xarray, which automatically loads the entire dataset when we 'quantify' (attach units), and we'd have to switch to using a dask backend to avoid this. We'll also be loading large arrays (and allocating additional ones) whenever we modify the normalisations.

@d7919 I think PR https://github.com/pyro-kinetics/pyrokinetics/pull/182 will enable us to read/write Pyrokinetics-style netCDF files, but it'll take some considerable reworking to have these built piecemeal from something like GENE output files.

**Comment by bpatel2107** [comment]
Well I am currently working on the mapping from pyro to IMAS IDS which in theory stores everything there, so we could use that, though it does have some restrictions which would be annoying. We could imagine something similar though. Having each object representing in a single file would be great.

We'll definitely start with the low hanging fruit

**Comment by bpatel2107** [comment]
Added this feature in #182
