### ISSUE TITLE
Default arakawa_zv in GENE template

### ISSUE THREAD

**Issue by mgiacomin** [bpatel2107/pyrokinetics#200]
@dake0795  Why is the default value of `arakawa_zv` set to false in the GENE template input file? 
https://github.com/pyro-kinetics/pyrokinetics/blob/3f0dfd195bdea912b2699b32eb5ca9d8b225f0bd/pyrokinetics/templates/input.gene#L38
Isn't this term required by energy conservation?

**Comment by dake0795** [comment]
This is what I was given by IFS for MTM simulations. Essentially turning it off increases the dissipation which you need to get linear agreement with GS2 and CGYRO. Without it you can get grid scale oscillations, but I haven’t tested this extensively.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: mgiacomin ***@***.***>
Sent: Friday, June 16, 2023 4:17:36 PM
To: pyro-kinetics/pyrokinetics ***@***.***>
Cc: Kennedy, Daniel ***@***.***>; Mention ***@***.***>
Subject: [pyro-kinetics/pyrokinetics] Default arakawa_zv in GENE template (Issue #200)


@dake0795<https://github.com/dake0795> Why is the default value of arakawa_zv set to false in the GENE template input file?
https://github.com/pyro-kinetics/pyrokinetics/blob/3f0dfd195bdea912b2699b32eb5ca9d8b225f0bd/pyrokinetics/templates/input.gene#L38
Isn't this term required by energy conservation?

**Comment by mgiacomin** [comment]
Thank you for your reply! 

There are indeed some regimes at high beta that are very prone to grid scale oscillations, especially in presence of unstable MTMs, and the only option to supress this numerical instability might be to set `arakawa_zv = .false.`.
On the other hand, I think that `pyrokinetics` should not set this parameter by default for the following reasons:
- The Arakawa scheme itself is energy (or in delta-f, entropy) conserving which increases confidence in a numerical implementation.
- There are other choices a user might try to mitigate grid scale oscillations via dissipation while keeping `arakawa_zv = .true.`. For instance one may set `arakawa_cons_bc = .false` that adds dissipative boundary conditions at the end of the tails in ballooning mode representation or use an upwind scheme by setting `hyp_z_with_dz_prefactor =  .true.` and `hyp_z = -1`.
- In most of the non-extreme cases, the grid scale oscillations indicate lack of convergence in `nx0`.

I am aware that these workarounds do not work in extreme high beta regimes, but I think that `pyrokinetics` should not target these extreme regimes by default. @dake0795 what do you think?

**Comment by dake0795** [comment]
I agree with these comments. I think it is sensible to keep the input template as "default" as possible.

**Comment by bpatel2107** [comment]
Just to weigh in, pyro should avoid going near issues like numerical dissipation as that can get quite messy, but the default setting should be the best physics case we have so having something like `arakawa_zv = .true.` seems to be best option.

If people want to tweak dissipation settings, that should be done manually, ideally by expert. The defaults shouldnt be tailored to specific regime

**Comment by dake0795** [comment]
I've created a PR to just remove the flag (meaning it is switched on by default).
