### ISSUE TITLE
coll_FLR in GENE

### ISSUE THREAD

**Issue by arkabokshi** [bpatel2107/pyrokinetics#233]
@dake0795  Should we add `coll_FLR =.true.` in GENE?  The code processes this as `.false.` if not specified I believe?

**Comment by arkabokshi** [comment]
![omega_gene](https://github.com/pyro-kinetics/pyrokinetics/assets/30498018/59711a13-9e5d-4cc6-863c-4e0ac55a8194)
![omega_gene](https://github.com/pyro-kinetics/pyrokinetics/assets/30498018/398cb46f-c41a-426a-a518-4771656aa31d)

Impact of `coll_FLR` term appears to be substantial.

**Comment by bpatel2107** [comment]
FLR terms are on by default in CGYRO/GS2. This sort of open up a wider issue of which collisional terms/operators are on by default in different codes. We can probably store this info in `numerics` similar to how it is done in the GKDB doc (section 4.6.4)

**Comment by arkabokshi** [comment]
Aside, would you not want the most "advanced" collisional operator options enabled in each GK code?

**Comment by bpatel2107** [comment]
This is beginning to step outside the remit of pyrokinetics (though not quite yet I think). Different codes have different models implemented so the most advanced for one code maybe be equivalent to a simpler model in another code. 

Part of me wants to keep the codes chosen default for collisions and let the user decide what to do (there may be a reason that FLR effects are off in GENE by default). But given that this leans more towards physics rather than numerical methods I would be fine to include a more sophisticated way to handle this.

**Comment by d7919** [comment]
I think I'd agree with leaning towards leaving switches as code defaults unless we have a very good reason not to do this. I think the role of pyrokinetics is to act as something which understands the approach of different codes but not as something which has opinions about how to use those codes?

One might consider documenting differences to consider and/or providing opinionated templates for different codes but I think the defaults should be decided by the codes themselves.

Of course we could change our mind and let the tool become opinionated, but I'm not sure that's something we'd want at this stage.

**Comment by mgiacomin** [comment]
I think a similar discussion was in #200, where we concluded that `pyrokinetics` should not change the default values in templates unless there is a very good reason to do so.

**Comment by bpatel2107** [comment]
Okay so I think we leave defaults as is, but leave open the option to set these terms in the future probably via something like `pyro.numerics.collisions.flr = True`

**Comment by arkabokshi** [comment]
I agree with the points, but in this case the rationale is slightly different:

- If we are choosing `sugma` operator, enabling this is "more physical" 
- the default behaviour with `sugama` is `coll_f_fm_on=F`, `coll_on_h=F` and `coll_FLR=F`. Since we have the other two as `.true.` it makes sense to enable the `coll_FLR` flag as well.  @dake0795 ?

EDIT:  That being said, it seems that the manual only recommends switching on the other two options for `sugama`. May be this isn't as important then...
