### ISSUE TITLE
Incorrect tripri in GS2?

### ISSUE THREAD

**Issue by mgiacomin** [bpatel2107/pyrokinetics#246]
The radial derivative of the triangularity for GS2 is computed from the triangularity shear as below
https://github.com/pyro-kinetics/pyrokinetics/blob/b1970ccbd4af754ec9f1a7c6971a40fcede7e73d/pyrokinetics/gk_code/gs2.py#L483-L485 

However the definition of the triangularity shear is $s_\delta = \frac{\rho}{1-\delta^2}\frac{\partial\delta}{\partial \rho}$, which implies $\delta\prime = s_\delta \sqrt{1-\delta^2}/\rho$. Isn't the factor $\sqrt{1-\delta^2}$ missing in `gs2.py`? @bpatel2107 @d7919

**Comment by bpatel2107** [comment]
In `Miller` we have: 

https://github.com/pyro-kinetics/pyrokinetics/blob/b1970ccbd4af754ec9f1a7c6971a40fcede7e73d/pyrokinetics/local_geometry/miller.py#L79-L81

which matches the definition in the paper
![image](https://github.com/pyro-kinetics/pyrokinetics/assets/15210802/0f3d68df-cad6-4ec5-8832-37b2d1f1d198)

![image](https://github.com/pyro-kinetics/pyrokinetics/assets/15210802/18cdfaab-ba4e-4c6c-bccf-e7a796bb6a52)

where $\delta = \frac{R_{Z,max} - R_0}{r}$ at $\theta  =\pi/2$


In GS2 `tri` isn't $\delta$ but $sin^{-1}(\delta)$

https://gyrokinetics.gitlab.io/gs2/page/namelists/index.html#theta_grid_parameters-tri
![image](https://github.com/pyro-kinetics/pyrokinetics/assets/15210802/b29e6f61-31b2-4caa-b5e3-1e33cf161efc)

You can see that we take this sine of the GS2 defn here
https://github.com/pyro-kinetics/pyrokinetics/blob/b1970ccbd4af754ec9f1a7c6971a40fcede7e73d/pyrokinetics/gk_code/gs2.py#L187-L188

When you take the derivative of `tri` $= sin^{-1}(\delta)$, you get `tripri` $=\frac{1}{1-\delta^2} \frac{\partial \delta}{\partial\rho}$ which is just missing the factor of $\rho$ from the Miller defn.

**Comment by mgiacomin** [comment]
Thank you very much for this very clear explanation!

**Comment by bpatel2107** [comment]
I spent a lot of time ripping my hair out over this 😆
