### ISSUE TITLE
New release v0.5.0

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#247]
In anticipation of the JOSS paper, shall we do a new release?

The only major thing in the works that may be close is GKW. @arkabokshi is this likely to be complete soon? Hoping to do the new release next week

**Comment by arkabokshi** [comment]
Sorry hadn't looked at it in a while -- shall make a start tomorrow and definitely aiming to have this done by the end of the month. :)

**Comment by LiamPattinson** [comment]
Would it possible to release version 0.5 soon-ish and 0.6 once GKW is added? I'd personally lean towards releasing more regularly, perhaps even after every PR merge.

**Comment by bpatel2107** [comment]
I'm not sure about every PR but I think once a month seems reasonable? If there's no harm in continual releases then I'm happy to release now (sounds like more releases is better anyways...)
