### ISSUE TITLE
GENE cocos bug?

### ISSUE THREAD

**Issue by arkabokshi** [bpatel2107/pyrokinetics#249]
Is this correct?

https://github.com/pyro-kinetics/pyrokinetics/blob/b680a09ffd465d207fc8712891b927e4cdabb3d3/pyrokinetics/gk_code/gene.py#L212 

Seems to return an error in almost all the cases that I have tried... GENE works out the "correct" sign internally, so this can be safely left out?

**Comment by bpatel2107** [comment]
This is what the manual says. Maybe it is out of date @dake0795?

![image](https://github.com/pyro-kinetics/pyrokinetics/assets/15210802/a64b869f-01c4-474e-a29d-8f8508ed3b55)
