### ISSUE TITLE
TGLF collision bug?

### ISSUE THREAD

**Issue by arkabokshi** [bpatel2107/pyrokinetics#251]
`TGLF.XNUE` is the electron-ion collision frequency.  Therefore to map to the electron-electron collision frequency, such as in https://github.com/pyro-kinetics/pyrokinetics/blob/038eb7aee01ce05e5b2fa74334048dc74f2ab57e/pyrokinetics/gk_code/tglf.py#L319 we should have `nu_ee = ne/ni * xnue`?

**Comment by bpatel2107** [comment]
It has the same definition as CGYRO so I think the choice of variable name is confusing
@hgd can you double check?

**Comment by arkabokshi** [comment]
If you see https://gafusion.github.io/doc/tglf/tglf_list.html#xnue, they are explicit in calling it electron-ion, so agreed, someone should check what the code actually does internally...

**Comment by bpatel2107** [comment]
I've double checked and they are the same as CGYRO, just an odd naming convention here
