### ISSUE TITLE
Proposal for plugin system

### ISSUE THREAD

**Issue by LiamPattinson** [bpatel2107/pyrokinetics#256]
I've been playing around with some of the more obscure Python packaging features, and I think I've found a way to improve the way we add new codes. Using _entry points_, we could design an interface for other libraries to hook into our code and register their own classes from within their own projects.

## Concept

Let's say we want to accept plugins for equilibrium reader classes. We could achieve this by adding something like the following to `equilibrium/__init__.py`:

```python
from importlib.metadata import entry_points

# the entry_points() function returns all entry point 'groups'
# Here, we only want the group called 'pyrokinetics.equilibrium'
# Note that this isn't a module path!
eq_entry_points = entry_points()["pyrokinetics.equilibrium"]

for entry_point in eq_entry_points:
    Equilibrium._factory[entry_point.name] = entry_point.load()
```

Meanwhile, if somebody were to write their own Pyrokinetics plugin that reads a new equilibrium type, they could register it with the `"pyrokinetics.equilibrium"` group by adding the following to their `pyproject.toml`:

```toml
[project.entry-points."pyrokinetics.equilibrium"]
vmec = "MyVMECLibrary.MyPyrokineticsPlugin:VMECReader"
```

This would add the class `VMECReader` to Pyrokinetics with the key `"vmec"`. If both packages were installed in the same Python environment, this would add VMEC functionality to Pyrokinetics without needing to explicitly import the VMEC library.

I made a little toy library called [`pyplugins`](https://github.com/LiamPattinson/pyplugins) which demonstrates this. It includes both an 'internal plugin', that ships with the core package, and an 'external plugin', which is a separate project. None of the libraries included directly `import` each other, but due to the way it's packaged it's possible to use all three via a common interface.

If we were to go all-in on a plugin architecture, it would be possible to reorganise Pyrokinetics as follows:

```bash
|__pyrokinetics
   |_ pyproject.toml
   |__ src
       |_ pyrokinetics # Define the core library, with no explicit reference to any codes
       |_ pyrokinetics-gs2 # GS2 plugin, adds input/output reader and normalisation scheme
       |_ pyrokinetics-cgyro # CGYRO plugin, see above
       |_ ... other GK codes ...
       |_ pyrokinetics-geqdsk # Plugin for G-EQDSK reading
       |_ pyrokinetics-transp # Define both equilibrium and kinetics plugins
```
So there would be a 'core' library, and then a collection of plugins that we ship alongside Pyrokinetics. These could potentially also be split off into their own repos if it was deemed necessary to isolate their development from the core code. However, it would be very time consuming and disruptive to reorganise everything like this, and in the meantime it should be possible to add these features without making substantial changes to the existing code.

## Pros

I think this would provide a cleaner way to integrate new codes into Pyrokinetics, as users wouldn't need to separately import Pyrokinetics and their own plugins. It would also allow us to do away with confusing decorators, although in their place we'd be adding complicated bits to `pyproject.toml` and `__init__.py` files.

If we went for an external plugin model:

- Easier for users to add their own codes.
- Users wouldn't have to import all the codes that they don't need.
- We could develop the core library and each plugin separately, leading to a more flexible release schedule. It would be possible to mix-and-match core library versions and plugin versions (within reason), while currently users have to wait for the entire library to update in order to get something like a small bug fix to a particular code. 

## Cons

I'm not aware of any significant downsides if we keep the code structure as it is and add this as an additional feature. However, if we move towards an external plugin model:

- Moving everything into external plugins would require a stable core interface, and I don't think we're there yet.
- Splitting everything across many repos could get messy and confusing, and could lead to dependency conflicts between each plugin.
- As far as I know, the normalisations part of the code currently isn't easily extendable without editing the `normalisations.py` file. It'd need a redesign to allow users to plug in new normalisation schemes.

## Further Resources

- [Setuptools docs on the topic](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#entry-points-for-plugins)
- [The PyPA specification](https://packaging.python.org/en/latest/specifications/entry-points/)

**Comment by d7919** [comment]
I really like the idea of a plugin system as

1. It puts the support of a code on the developers of that code -- they should be the experts so are likely best placed to do this. There's a downside here too in that if the developers don't support/maintain their plugin users may get a bad impression of pyrokinetics or there may be multiple attempts to add support for the same code which can get confusing.
2. It requires a well documented and stable code base! It also forces us to think about the separation of concerns etc. (not that we haven't).
3. It forces us to document clearly how to add support for a new code of a particular type.
4. We've been considering adding diagnostics etc. -- I would imagine that this is one place where lots of plugins could be useful.
5. People could choose to maintain their own plugin for a particular code tuned to some particular piece of work etc., effectively overriding the "core' implementation whilst still being able to easily get updates to the pyrokinetics core.

**Comment by bpatel2107** [comment]
This is an interesting idea! Making it more flexible in general seems like a good idea and I agree this can be quite useful in certain scenarios like diagnostics as @d7919 mentions.

The concern I have is one you raised that having lots of repos could become quite messy. I imagine that once a plugin becomes sufficiently well developed it may be worth keeping that in the main repo to ensure everything stays well linked but it would definitely make the development a lot easier.

Another concern would be how to structure the core interface. Eventually we may want to extend pyro to work on a range of different gyrokinetics regimes like full-f, global or even edge turbulence codes. We would need to ensure that the core interface is able to handle such scenarios. Definitely doable but we just need to think it through.

**Comment by d7919** [comment]
I think there could be a series of "core" plugins which we maintain in (separate) repositories but in this project. Then if there are other repositories offering plugins elsewhere that's kind of not our problem?

**Comment by bpatel2107** [comment]
Done in #258
