### ISSUE TITLE
v0.6.0 release

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#264]
I think we are due another release. I would like for #261 and #263 to be merged before this. It would be good for #252 to be merged but the documentation doesn't really impact the actual code so that's not a big deal.

Maybe be worth addressing the issues in #262 before we release too.

Will aim for this to be released by end of next week so please mention any other features that you'd like to include. I would like to add in the ability to read in GACODE files which have both the `Equilibrium` and `Kinetics` data (#265)

**Comment by ZedThree** [comment]
Technically, I think this would be v0.6.0 :)

**Comment by bpatel2107** [comment]
I'd like to release when #265 is merged. 

Are there any other features people would like to be completed before this new release?

**Comment by LiamPattinson** [comment]
Issue https://github.com/pyro-kinetics/pyrokinetics/issues/274 shouldn't take long, especially if we're just moving imports around.
