### ISSUE TITLE
GS2 range grids defaults ky_min/max to strings

### ISSUE THREAD

**Issue by d7919** [bpatel2107/pyrokinetics#269]
https://github.com/pyro-kinetics/pyrokinetics/blob/167e6824a7244fb1d8ad1db3488d3785903e1572/src/pyrokinetics/gk_code/gs2.py#L299

Note if the input file doesn't have `aky_min/aky_max` then we get a default of `"0.0"` i.e. a string. These should probably be floats.

**Comment by bpatel2107** [comment]
Fixed in #278
