### ISSUE TITLE
Dealing with GS2's changes to "input_file" in the netCDF output

### ISSUE THREAD

**Issue by mehfoos** [bpatel2107/pyrokinetics#272]
https://github.com/pyro-kinetics/pyrokinetics/blob/9876bb3eb28cae2f7f41c4f6e9c16225d3e19182/src/pyrokinetics/gk_code/gs2.py#L717C86-L717C86

In the "next" branch of GS2, the format of "input_file" seems to be different (included an attachment trying to illustrate this). 
![GS2 out nc input_file format change](https://github.com/pyro-kinetics/pyrokinetics/assets/15526657/a68b9ee7-171b-43ce-aee0-b9e956d3fd1c)
Not sure if it's unique to "next" branch.
This seems to result in pyrokinetics/gk_code/gs2.py -> _get_raw_data failing at:
`input_str = "\n".join((line.decode("utf-8") for line in input_file.data))`

Not sure if this is the incorrect way to handle the issue, and whether it causes problems downstream, but I've tried this workaround to get past it:
`input_str = str(input_file.data,'UTF-8')`

**Comment by bpatel2107** [comment]
This should be addressed in #271 which is under review

**Comment by bpatel2107** [comment]
Fixed in #271
