### ISSUE TITLE
Support GS2 input files using toroidal modes (n0) as opposed to binormal wavenumber (aky)

### ISSUE THREAD

**Issue by mehfoos** [bpatel2107/pyrokinetics#273]
_[not sure if "enhancement" or an issue as such]_

GS2 seems to allow using [toroidal modes (n0)](https://gyrokinetics.gitlab.io/gs2/page/namelists/index.html#kt_grids_single_parameters-n0) as opposed to [binormal wavenumber (aky)](https://gyrokinetics.gitlab.io/gs2/page/namelists/index.html#kt_grids_single_parameters-aky) for input configuration.

A workaround provided by @mgiacomin was to change input files manually and set aky to = rhostar_single * n0 *drhodpsi. The value of drhodpsi is something that can be extracted from the output file. Similar process can be used for nn0, nn0_min, nn0_max conversions to naky, aky_min, aky_max respectively, for kt_grids_range_parameters.

Can pyrokinetics implement this?

**Comment by bpatel2107** [comment]
We should be able to calculate everything here internally in pyro if we know the value of $\rho_*$. If we know the normalisations then this is possible so it should be straightforward to do

**Comment by d7919** [comment]
If the user specifies `n0` then then have to specify `rhostar` in the input file as well so we should always have that information.
