### ISSUE TITLE
Optional dependencies to speed up import

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#274]
Currently doing `import pyrokinetics` can take over 30 seconds, likely due to the large number of imports. We should look into having optional dependencies to speed up the import time and move imports so they are inside relevant functions

**Comment by bpatel2107** [comment]
Found this nifty library to breakdown the import time of a module
https://github.com/nschloe/tuna

Running this on the unstable branch

```
python -X importtime -c "import pyrokinetics" 2> pyrokinetics.log
tuna pyrokinetics.log
```

shows that 1/3 of the import time is on `xarray` so speeding that up would be helpful if possible. Another 1/3 comes from `jetto_tools`

![image](https://github.com/pyro-kinetics/pyrokinetics/assets/15210802/a341a702-bcaa-4fd2-b926-fe7a7e5e46f6)
![image](https://github.com/pyro-kinetics/pyrokinetics/assets/15210802/fd635373-1574-4903-ae90-9b77e26631df)


Note doing this on the `feature/gacode_reader` branch adds essentially no time

**Comment by ZedThree** [comment]
Might not be much we can do about xarray -- it's worth updating it though, as they have sped up their import time recently.

There's some low hanging fruit in `jetto_tools` by just not importing `IPython.embed` everywhere.

OMAS is a little trickier, in that we would need to change their build system and get them to distribute binaries instead of dynamically running cython on import. But that is possible.

Just moving the `jetto_tools` import into the functions that use it is a significant speed up for us.

Our `units` module takes a long time, but that's because we have to create the units registry. I'm not sure of a nice way around that off the top of my head.

**Comment by LiamPattinson** [comment]
This is a neat tool! Interestingly, I get very different results on my own machine:

![import_time](https://github.com/pyro-kinetics/pyrokinetics/assets/14332134/805730d3-840b-45bf-acdd-955a53685fe3)

To break it down:

- Xarray 15%
- Matplotlib 11%
- pint 11%
- pint xarray 18% (?!)
- Our own units work ~15%
- jetto_tools 16%
- The rest

I'm surprised that almost half of the import time is coming just from the units. I think we should be able to get a significant speed up by moving the Matplotlib/Xarray/Jetto stuff only to the functions that use them, but I don't know about speeding up our own units. If the time is being taken up defining unit systems for each GK code, perhaps these could be defined lazily only if the user is using those codes?

One issue with moving to lazy imports is that type hinting might get confused, as that needs libraries imported throughout the module. The solution to that will be:

```python
# Type hints are all evaluated as strings, so don't break if libraries are missing
from __future__ import annotations

# Import libraries only if building docs/running mypy etc
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    import xarray as xr
    ...
```

I'm not 100% sure if Sphinx activates `TYPE_CHECKING`, so will have to experiment.

---

With regards to moving certain features into optional dependencies, I'm not sure how best  to do this fairly. We could take an equitable approach and say "no external codes that require a special library are supported by default", and I think that would include freeqdsk, pygacode, jetto-tools, and idspy. Or we could just make a judgment of how likely our users are to make use of certain features, or how likely the dependencies are to break things (i.e. pygacode requiring a Fortran compiler).
