### ISSUE TITLE
Error when using GS2 grid_option = 'range'

### ISSUE THREAD

**Issue by mehfoos** [bpatel2107/pyrokinetics#276]
**Brief description**: When scanning over multiple binormal wavenumbers (or toroidal modes for that matter), using [grid_option = 'range'](https://gyrokinetics.gitlab.io/gs2/page/namelists/index.html#kt_grids_knobs-grid_option) in GS2, pyrokinetics throws an error.

**Versions affected**: This happens on recent commits (including SHA 167e6824a7244fb1d8ad1db3488d3785903e1572 and 6b475bff34135a5ff8ee0aa8a7fc600e79b1c9f4), but does not seem to occur with older version (SHA 408e25a20c4d12e8ca8233b3d772504dc404f16b, for instance).

**Possible cause**: David had mentioned that it may be to do with the shape of the phase array, which should be [ntheta0, naky] in size.

**Some additional details**: The last error traced back to a file outside of library dependencies seems to be in pyrokinetics/gk_code/gk_output.py -> _normalise_linear_fields (not sure if this is the root cause; there may be issues upstream; I've pasted the error thrown when trying to run)
This only seems to happen in scanning/range simulations, and not if I just use one value for n0,or ky in GS2.
Where does it fail: It is traced to the multiplication of phase by amplitude in:
`fields[field_name] *= phase / amplitude`
In my specific case, with 30 points of binormal wavenumbers (naky = 30) I've noted some properties of phase and amplitude (phase is complex): phase.shape is (1, 30, 1, 30). amplitude.shape is (1, 30). type(phase) is <class 'pint.util.Quantity'>. type(amplitude) is<class 'numpy.ndarray'>.
This ultimately results in an error thrown by pint's quantity.py: ValueError: operands could not be broadcast together with shapes (193,1,30,246) (1,30,1,30) (193,1,30,246).

**Comment by bpatel2107** [comment]
Thanks for the detailed bug report, made it much easier to see what's happening. Essentially `pyro` doesn't fully support running multiple linear simulations with `range`. 

What is happening here is that `pyro` recognises that this is a linear simulation and is attempting to normalise the output fluxes using the fields. To do that it has to multiply by a phase and divide by an amplitude to get it in the correct normalisation (which was added recently hence it working before but not now). The amplitude should be being calculated correctly but the phase doesn't seem to be. The fix should be relatively straightforward as we just need the array sizes to match up as there is a single phase/amplitude for each `ky` 

See section 5.5.3 here for details
https://gitlab.com/gkdb/gkdb/raw/master/doc/general/IOGKDB.pdf

**Comment by mehfoos** [comment]
Thanks for the quick reply and suggestions for a workaround.

**Comment by bpatel2107** [comment]
Fixed in #277
