### ISSUE TITLE
Betae not set in CGYRO input file when converting a gs2 input file

### ISSUE THREAD

**Issue by whornsby82** [bpatel2107/pyrokinetics#298]
The value of beta is not carried over when converting the following input file (assuming betae_unit) is the parameter:

&kt_grids_knobs
    grid_option = 'single'
/

&kt_grids_single_parameters
    aky = 0.27389728976666694
    theta0 = 0.0
/

&theta_grid_parameters
    ntheta = 128
    nperiod = 9
    akappa = 2.66
    akappri = -0.25
    rhoc = 0.67
    tri = 0.3400000000000002
    tripri = 0.25
    shat = 0.87
    qinp = 8.168067652666569
    r_geo = 1.84
    rmaj = 1.84
    shift = -0.44
    geotype = 0
/

&theta_grid_knobs
    equilibrium_option = 'eik'
/

&theta_grid_eik_knobs
    irho = 2
    iflux = 0
    s_hat_input = 0.829079150499802
    beta_prime_input = -0.64
    local_eq = .true.
    bishop = 4
    equal_arc = .false.
    writelots = .true.
/

&le_grids_knobs
    ngauss = 8
    negrid = 16
    bouncefuzz = 1e-08
/

&dist_fn_knobs
    adiabatic_option = 'iphi00=2'
    opt_source = .true.
    def_parity = .true.
    even = .false.
/

&fields_knobs
    field_option = 'implicit'
    response_dir = 'response'
/

&knobs
    fphi = 1.0
    fapar = 1.0
    fbpar = 0.0
    delt = 0.02
    nstep = 80000
    wstar_units = .true.
/

&layouts_knobs
    layout = 'xyles'
/

&collisions_knobs
    collision_model = 'default'
/

&species_knobs
    nspec = 3
/

&species_parameters_1
    z = 1.0
    mass = 1.0
    dens = 0.5
    temp = 1.0593220338983051
    tprim = 0.0
    fprim = 1.0905265157176203
    uprim = 0.0
    vnewk = 0.0004750569354704837
    type = 'ion'
    bess_fac = 1.0
/

&dist_fn_species_knobs_1
    fexpr = 0.48
    bakdif = 0.05
/

&species_parameters_2
    z = 1.0
    mass = 1.4975
    dens = 0.5
    temp = 1.0593220338983051
    tprim = 0.0
    fprim = 1.0905265157176203
    uprim = 0.0
    vnewk = 0.00038788236355765326
    type = 'ion'
    bess_fac = 1.0
/

&dist_fn_species_knobs_2
    fexpr = 0.48
    bakdif = 0.05
/

&species_parameters_3
    z = -1
    mass = 0.0002724
    dens = 1.0
    temp = 1.0
    tprim = 1.5930155903555336
    fprim = 2.1810530314352405
    uprim = 0.0
    vnewk = 0.057574078389447655
    type = 'electron'
    bess_fac = 1.0
/

&dist_fn_species_knobs_3
    fexpr = 0.48
    bakdif = 0.05
/

&init_g_knobs
    ginit_option = 'restart'
    chop_side = .false.
    phiinit = 1e-05
    restart_dir = 'restart'
/

&gs2_diagnostics_knobs
    write_ascii = .true.
    write_omega = .true.
    write_final_fields = .true.
    write_fields = .true.
    write_phi_over_time = .true.
    write_bpar_over_time = .true.
    write_apar_over_time = .true.
    write_nl_flux_dist = .true.
    write_fluxes = .true.
    write_nl_flux = .true.
    nwrite = 30
    navg = 10
    omegatol = 0.0001
    omegatinst = 500.0
    nsave = 5000
    save_for_restart = .true.
    write_final_epar = .true.
/

&parameters
    beta = 0.11622940887149895
    tite = 1.0
    zeff = 1.0
/

&diagnostics_config
    nwrite = 100000000
/

the CGYRO input file created is:

N_ENERGY = 16
E_MAX = 8
N_XI = 16
N_THETA = 128
THETA_PLOT = 128
N_RADIAL = 18
N_TOROIDAL = 1
N_FIELD = 2
DELTA_T = 0.014142135623730949
PRINT_STEP = 100
MAX_TIME = 1131.3708498984759
FREQ_TOL = 0.001
KY = 0.19367463094262696
PX0 = 0.0
BOX_SIZE = 1
NONLINEAR_FLAG = 0
EQUILIBRIUM_MODEL = 2
RMIN = 0.67
RMAJ = 1.84
ZMAG = 0.0
DZMAG = 0.0
KAPPA = 2.66
S_KAPPA = -0.06296992481203008
DELTA = 0.33348709214081457
S_DELTA = 0.157911406475998
ZETA = 0.0
S_ZETA = 0.0
SHIFT = -0.44
BETAE_UNIT = 0.0
Q = 8.168067652666569
S = 0.829079150499802
BETA_STAR_SCALE = 1.0
COLLISION_MODEL = 4
NU_EE = 0.0814220424994886
Z_EFF = 1.0
Z_EFF_METHOD = 1
N_SPECIES = 3
Z_1 = 1.0
DENS_1 = 0.5
TEMP_1 = 1.0593220338983051
MASS_1 = 1.0
DLNNDR_1 = 1.0905265157176203
DLNTDR_1 = 0.0
Z_2 = 1.0
DENS_2 = 0.5
TEMP_2 = 1.0593220338983051
MASS_2 = 1.4975
DLNNDR_2 = 1.0905265157176203
DLNTDR_2 = 0.0
FIELD_PRINT_FLAG = 1
MOMENT_PRINT_FLAG = 1
IPCCW = 1
BTCCW = 1
MASS_3 = 0.0002724
Z_3 = -1
DENS_3 = 1.0
TEMP_3 = 1.0
DLNTDR_3 = 1.5930155903555336
DLNNDR_3 = 2.1810530314352405
MACH = 0.0
GAMMA_P = -0.0
GAMMA_E = -0.0

**Comment by bpatel2107** [comment]
Just tried on the latest release and it seems to work for me

`
pyro convert CGYRO test.gs2
`

Gets me 
`
BETAE_UNIT = 0.01193844070036381
`

Can you double check the version and re-install via pip?

**Comment by whornsby82** [comment]
I pulled the latest unstable version, it says: pyrokinetics-0.6.1

**Comment by bpatel2107** [comment]
Sometimes you need to re-install via pip. Can you do 
`python -m pip install -e .` 
in the pyrokinetic directory?

**Comment by whornsby82** [comment]
Im getting:

ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/ir-horn2/Code/pyrokinetics

(A "pyproject.toml" file was found, but editable mode currently requires a setup.py based build.)




From: Bhavin Patel ***@***.***>
Date: Wednesday, 6 March 2024 at 17:13
To: pyro-kinetics/pyrokinetics ***@***.***>
Cc: Hornsby, William ***@***.***>, Author ***@***.***>
Subject: Re: [pyro-kinetics/pyrokinetics] Betae not set in CGYRO input file when converting a gs2 input file (Issue #298)

Sometimes you need to re-install via pip. Can you do
python -m pip install -e .
in the pyrokinetic directory?

**Comment by bpatel2107** [comment]
Can you upgrade pip first?

**Comment by whornsby82** [comment]
OK, done, but then it seems to install an old version:

Successfully installed pyrokinetics-0.2.0a1.dev53+g89e5153


From: Bhavin Patel ***@***.***>
Date: Wednesday, 6 March 2024 at 17:17
To: pyro-kinetics/pyrokinetics ***@***.***>
Cc: Hornsby, William ***@***.***>, Author ***@***.***>
Subject: Re: [pyro-kinetics/pyrokinetics] Betae not set in CGYRO input file when converting a gs2 input file (Issue #298)

Can you upgrade pip first?

**Comment by bpatel2107** [comment]
Hmmm that's odd. Are you definitely in the pyro directory? Can't imagine why it would do that. Or you can specify the version like

`python -m pip install pyrokinetics==0.6.1`

**Comment by whornsby82** [comment]
OK.  If I use your command like above, the input.cgyro looks ok, if I do:

from pyrokinetics import Pyro
pyro = Pyro(gk_file='../gs2.in')
pyro.gk_code = "CGYRO"
pyro.write_gk_file(file_name="./input.cgyro")

The betae values aren't updated:

< BETAE_UNIT = 0.0
---
> BETAE_UNIT = 0.01193844070036381
32c32
< BETA_STAR_SCALE = 1.0
---
> BETA_STAR_SCALE = 1.1170685008114143
62c62
< GAMMA_E = -0.0
---
> GAMMA_E = 0.0

**Comment by bpatel2107** [comment]
Ooh that's a sneaky one! Found the issue which came from doing `pyro.gk_code = "CGYRO"`. Currently it tries to calculate `beta` from the Kinetics/Equilibrium (which doesn't exist in this case) even if `beta` has already been set in the Numerics object. Will push a simple fix and add a test for this tomorrow.

You'll need to install the github version though, not from PyPi.
