### ISSUE TITLE
When querying parameters, they should always provide a unit, even if no unit is present

### ISSUE THREAD

**Issue by whornsby82** [bpatel2107/pyrokinetics#308]
When querying parameters, the return is sometimes and xarray Quantity (e.g local_species['ion1'].inverse_lt gives, 5.166073892153321 / lref_minor_radius) and sometimes just a number (e.g q, s_hat).  This should be consolidated to a single type of return to make automation cleaner

**Comment by bpatel2107** [comment]
This is done now so closing. Just a note, when setting a variable if a unit is not specified then it will maintain the same unit.
