### ISSUE TITLE
Second beta namelist parameter in gs2 input file on convert

### ISSUE THREAD

**Issue by jfparisi** [bpatel2107/pyrokinetics#322]
Converting a CGYRO to GS2 input file gives two beta namelist parameters, one of which (in &parameters) doesn't do anything (at least from my tests). It might be worth removing &parameters namelist in GS2 input file?

**Comment by bpatel2107** [comment]
I believe this is due to a change in beta's location in GS2. This was updated correctly when making new GS2 files but the beta in  &parameters was left in the template file we store. We should just correct that.

**Comment by bpatel2107** [comment]
Fixed in #323
