### ISSUE TITLE
pyro_to_ids fails when outside of pyrokinetics directory

### ISSUE THREAD

**Issue by jmcclena** [bpatel2107/pyrokinetics#330]
fails due to not finding git repo

branch: `enhancements/imas_update_v3.4`

error: 
```
File [~/miniconda3/lib/python3.11/site-packages/pyrokinetics/databases/imas.py:270](http://localhost:8888/lab/tree/~/miniconda3/lib/python3.11/site-packages/pyrokinetics/databases/imas.py#line=269), in pyro_to_imas_mapping(pyro, comment, time_interval, reference_values, ids)
    262 ids_properties = {
    263     "provider": "pyrokinetics",
    264     "creation_date": str(datetime.now()),
    265     "comment": comment,
    266     "homogeneous_time": 1,
    267 }
    269 ids_properties = gkids.IdsProperties(**ids_properties)
--> 270 repo = git.Repo(search_parent_directories=True)
    271 sha = repo.head.object.hexsha
    272 code_library = [
    273     {
    274         "name": "pyrokinetics",
   (...)
    278     }
    279 ]

File [~/miniconda3/lib/python3.11/site-packages/git/repo/base.py:276](http://localhost:8888/lab/tree/~/miniconda3/lib/python3.11/site-packages/git/repo/base.py#line=275), in Repo.__init__(self, path, odbt, search_parent_directories, expand_vars)
    273 # END while curpath
    275 if git_dir is None:
--> 276     raise InvalidGitRepositoryError(epath)
    277 self.git_dir = git_dir
    279 self._bare = False

InvalidGitRepositoryError: [/Users/mcclenaghan/programming/python/jupyter_notebooks](http://localhost:8888/lab/tree/mgkdb.ipynb)
```

From what I've read, I don't think there is a way to know the commit hash of an installed package. Would it make sense to wrap this logic in a try-except?

**Comment by bpatel2107** [comment]
Yeah I saw this too at times I had a fix but that broke the testing see here

https://github.com/pyro-kinetics/pyrokinetics/actions/runs/8264030375/job/22606734500
https://github.com/pyro-kinetics/pyrokinetics/pull/301/commits/0bfa669930b34c78bde6f113fa49a6d5eb237454

I can add a try-except and we store the version of pyrokinetics anyway which _should_ be enough

**Comment by LiamPattinson** [comment]
I've worked on other projects where this problem of getting a git commit hash from an installed library has appeared. It looks like it should be possible to get this info from `setuptools-scm` at install/build time, but it will require a custom plugin, and it isn't clear from the docs how to do this. It's something I could take a look at.

**Comment by bpatel2107** [comment]
Sounds good, this does seem like a minor patch though so I will push a temporary try-except for now and we can fix this when possible. The commit hash isn't really used for much beyond data providence and who cares about that...

**Comment by bpatel2107** [comment]
@jmcclena can you pull the latest version of `imas_update_v3.4` and see if the latest changes have helped. Some wizardry has occurred.

**Comment by jmcclena** [comment]
@bpatel2107 It works now with the latest version. Thanks!
