### ISSUE TITLE
Bugs reading pFile (#1)

### ISSUE THREAD

**Issue by mrhardman** [bpatel2107/pyrokinetics#353]
Trying to read a `.pfile` using the equilibrium file reader, 

```
pyro = Pyro(
     eq_file=eq_file,
     eq_type="GEQDSK",
     kinetics_file=kinetics_file,
     kinetics_type="pFile",
     gk_file=gk_file,
 )
pyro.load_local(psi_n=0.5, local_geometry="Miller")
```
I have come across this error, which looks to be in the pyrokinetics source:
```
File "/*/pyrokinetics/kinetics/pfile.py", line 220, in read_from_file
    fast_ion_mass = ion_nucleons * deuterium_mass / 2.0
UnboundLocalError: local variable 'ion_nucleons' referenced before assignment
```
It looks like ion_nucleons here should be replaced by fast_ion_nucleons.

Spotted originally by Peter Buxton.

**Comment by bpatel2107** [comment]
That is a typo, good spot. The line should be 

`fast_ion_mass = fast_ion_nucleons * deuterium_mass / 2.0`

Will make a quick PR to fix
