### ISSUE TITLE
Bugs installing pyro

### ISSUE THREAD

**Issue by mrhardman** [bpatel2107/pyrokinetics#354]
After fixing locally #353, I found the following error after attempting to pull the latest unstable and reinstall pyrokinetics. It looks like the basic package has built incorrectly: what has gone wrong?

```
Traceback (most recent call last):
  File "*", line 1, in <module>
    from pyrokinetics import Pyro, template_dir
  File "*/pyrokinetics/__init__.py", line 35, in <module>
    from .pyro import Pyro
  File "*/pyrokinetics/pyro.py", line 26, in <module>
    from .gk_code import (
  File "*/pyrokinetics/gk_code/__init__.py", line 13, in <module>
    from .ids import GKOutputReaderIDS  # noqa
  File "*/pyrokinetics/gk_code/ids.py", line 7, in <module>
    from idspy_dictionaries import ids_gyrokinetics
  File "*/idspy_dictionaries/ids_gyrokinetics/__init__.py", line 5, in <module>
    from idspy_dictionaries.ids_gyrokinetics.idspy_gyrokinetics import (
  File "*/idspy_dictionaries/ids_gyrokinetics/idspy_gyrokinetics.py", line 5, in <module>
    from ..dataclasses_idsschema import _IDSPYDD_USE_SLOTS,IdsBaseClass
ImportError: cannot import name '_IDSPYDD_USE_SLOTS' from 'idspy_dictionaries.dataclasses_idsschema' (/*/idspy_dictionaries/dataclasses_idsschema.py)
```

**Comment by bpatel2107** [comment]
This is due to an older version of `idspy_toolkit` you have installed. Please go into the base pyrokinetics directory and do the following to update your installed python packages

`python -m pip install -e .`

**Comment by mrhardman** [comment]
In the end a new virtual environment was required to fix this (as I wasn't sure if this was an external library problem or a pyro problem, I did a new install). `$python -m pip install -e .` did not update the dependency properly.

**Comment by bpatel2107** [comment]
Another possibility is that you have several versions installed. You can try to keep uninstalling it until python can't find it anymore and then reinstall (`python -m pip uninstall pyrokinetics`)

**Comment by mrhardman** [comment]
I did try `python -m pip uninstall pyrokinetics` as well, but it states that there are no files found to uninstall. Perhaps that is because I have an editable install?

**Comment by bpatel2107** [comment]
Did you try uninstalling it in the pyrokinetics directory or the directory above that as that could be confusing pip. Try a completely random one  away from pyrokinetics?

**Comment by mrhardman** [comment]
The kind of error message that I see is this one, when I try to uninstall pyrokinetics:

```
 Attempting uninstall: pyrokinetics
    Found existing installation: pyrokinetics 0.0.0
    Not uninstalling pyrokinetics at /*/pyrokinetics, outside environment /*
    Can't uninstall 'pyrokinetics'. No files were found to uninstall.

```

This command (`python3 -m pip uninstall pyrokinetics`) was made in the top directory of pyrokinetics

**Comment by bpatel2107** [comment]
Hmm... this is odd. Try the uninstall in a different directory? Otherwise this is a weird pip issue I don't understand. I doubt the `editable` flag is important here.

**Comment by mrhardman** [comment]
OK, `python3 -m pip uninstall pyrokinetics` from a different directory did find files to uninstall.

Fortunately if someone sees this they only need to know that a new virtual environment is enough to work around whatever is going on here : )

**Comment by bpatel2107** [comment]
Glad it is working now!
