### ISSUE TITLE
Why is beta_star_scale /= 1 when input.cgyro generated from .pfile?

### ISSUE THREAD

**Issue by mrhardman** [bpatel2107/pyrokinetics#356]
Using commands like those below, I generate an `input.cgyro` file from the template GEQDSK and pFiles, but I note that `beta_star_scale = 22.816660835526864`. Is this due to inconsistency between the templates (which is therefore not a bug), or due to a bug in pyrokinetics?

```
  eq_file = template_dir / "test.geqdsk"
    # Kinetics data file
    kinetics_file = template_dir / "pfile.txt"
    # Load up pyro object
    pyro = Pyro(
        eq_file=eq_file,
        eq_type="GEQDSK",
        kinetics_file=kinetics_file,
        kinetics_type="pFile",
    )

    pyro.local_geometry = "Miller"
    # Generate local Miller parameters at psi_n=0.5
    pyro.load_local_geometry(psi_n=0.5)
    pyro.load_local_species(psi_n=0.5)
    pyro.write_gk_file(file_name=base_path / "test_pfile.cgyro", gk_code="CGYRO")

```

**Comment by bpatel2107** [comment]
This is due to a inconsistency in the templates as they are not all the same case. Quite difficult to get all in the same scenario in different formats.
