### ISSUE TITLE
Conversion utility exe

### ISSUE THREAD

**Issue by d7919** [bpatel2107/pyrokinetics#46]
A common use case (for me at least) is to convert input files between formats. It might be nice to provide a small tool as part of the install, e.g. 

`pyro-convert -i input.in -o input.cgyro`

or similar.

**Comment by bpatel2107** [comment]
We would need to find a way to specify the input and output codes (or automatically check what the input is)

**Comment by d7919** [comment]
Yes we either need some convention/automatic detection or additional flags like so something like

`pyro-convert -i gs2 -o cgyro input.in > input.cgyro`

or some syntax for hints 

`pyro-convert -i input.in:GS2 -o input.cgyro:CGYRO`

**Comment by bpatel2107** [comment]
Done in #168

**Comment by LiamPattinson** [comment]
I actually wasn't aware of this issue when I started on my PR! I'd be open to any changes to the interface in a future PR.
