### ISSUE TITLE
Error in geqdsk equilibrium

### ISSUE THREAD

**Issue by d7919** [bpatel2107/pyrokinetics#49]
In trying to generate a local miller equilibrium from the highq0tdotp case on surface psi_N=0.5 I hit the following

>   File "pyro_generate_inputs.py", line 10, in <module>
>     kinetics_type="SCENE",
>   File "/users/dd502/.local/lib/python3.7/site-packages/pyrokinetics/pyro.py", line 53, in __init__
>     self.load_global_eq()
>   File "/users/dd502/.local/lib/python3.7/site-packages/pyrokinetics/pyro.py", line 139, in load_global_eq
>     self.eq = Equilibrium(self.eq_file, self.eq_type, **kwargs)
>   File "/users/dd502/.local/lib/python3.7/site-packages/pyrokinetics/equilibrium.py", line 44, in __init__
>     self.read_geqdsk(**kwargs)
>   File "/users/dd502/.local/lib/python3.7/site-packages/pyrokinetics/equilibrium.py", line 142, in read_geqdsk
>     surface_R, surface_Z = self.get_flux_surface(psi_n=i_psiN)
>   File "/users/dd502/.local/lib/python3.7/site-packages/pyrokinetics/equilibrium.py", line 184, in get_flux_surface
>     paths = con.collections[1].get_paths()
> IndexError: list index out of range

Changing `paths = con.collections[1].get_paths()` to `paths = con.collections[0].get_paths()` appears to allow me to proceed as expected.

**Comment by bpatel2107** [comment]
It seems like it has only found 1 contour at the specified value. Normally it find one contour at 0 and one at `psi_n`. Simple check of len(con.collections) will fix this

**Comment by d7919** [comment]
Is there a reason that you include the 0 level in the contour call?
