### ISSUE TITLE
Inconsistency in gs2 normalisation handling?

### ISSUE THREAD

**Issue by d7919** [bpatel2107/pyrokinetics#50]
In testing a round trip converting from a custom gs2 input to cgyro and then back to gs2 I find three parameters change, two in the least significant digit, so basically identical, but one by 20%.

The original input file is setup with R_geo /= rmaj whilst pyrokinetics likes R_geo=rmaj. This changes the location at which the normalising magnetic field is evaluated. Hence I would expect the round trip to 

1. change R_geo and rmaj to be equal
2. scale anything using the normalising magnetic by a factor like R_geo/rmaj

In particular, I'd expect the rescaling to change beta and beta_prime. It seems that beta_prime is changing (this is the parameter which varies a lot) but beta is being held more or less fixed (this is one of the parameters which is changing in the least significant digit). Further, neither of R_geo and rmaj are changed.

As it stands the round trip input either has an incorrect beta_prime (as it has been scaled for a different normalising field)  or beta and R_geo/rmaj are incorrect as they have not been modified to reflect the change in normalising field. 

On a more minor note gs2 can store the normalising parameters in an input namelist. It would be nice if pyrokinetics would write these where possible and could see if these already exist in a source input file and scale as appropriate.

**Comment by d7919** [comment]
To reproduce you need an input file containing something like

> r_geo  = 2
> rmaj = 1.0
> beta_prime_input = -1.0
> beta = 0.5

with a miller equilibrium treatment (local_eq = T)
Then something like
~~~
pp = Pyro(gk_file = 'input.in', gk_type = 'GS2')
pp.write_gk_file('new.in')
~~~
should be enough. Comparing new and input I would expect to find that r_geo is changed to 1 and that the beta values have been scaled by 2. In reality I find that all parameters are unchanged except beta_prime_input which is scaled as expected.

**Comment by bpatel2107** [comment]
I've found the issue which is that miller.Rgeo is never overwritten with Rmaj. I don't think Rgeo is doing anything useful so there's no point storing it. I'll make a PR that removes it entirely from the Miller object and just uses it for renormalisation.
