### ISSUE TITLE
Minor : Pyro init takes gk_type but then we set gk_code to change type

### ISSUE THREAD

**Issue by d7919** [bpatel2107/pyrokinetics#51]
Fairly minor but I always forget that the init call takes gk_type but we change the type of the instance by setting the gk_code property. Could these have the same name?

**Comment by bpatel2107** [comment]
We could and I've been meaning to do this. It will break a lot of people's code. Is there a good way to warn people about this? Maybe add in a deprecation warning?

**Comment by d7919** [comment]
My guess would be something like
~~~
__init__(....., gk_code = None, gk_type = None, ... ):
     if gk_type is not None:
             print(message about upgrading)
             if gk_code is not None and gk_code /= gk_type:
                 abort as inconsistent
             gk_code = gk_type
  ~~~
for a release or two.

**Comment by ZedThree** [comment]
[`DeprecationWarning`](https://docs.python.org/3/library/exceptions.html?highlight=deprecationwarning#DeprecationWarning) was made for this :slightly_smiling_face:
