### ISSUE TITLE
load_gk_output doesn't pay attention to path of gk_file

### ISSUE THREAD

**Issue by d7919** [bpatel2107/pyrokinetics#56]
When creating a pyro object one can point to a gk file in a different directory. Using load_gk_output always tries to read output from the current directory. This could be confusing and it might be that we want to get the directory storing the gk_file and use that as the default location in which to look for output files.

**Comment by bpatel2107** [comment]
Pyro does store that information under `pyro.run_directory`. When calling `pyro.load_gk_output`, it looks at each `gk_code` object and uses the bespoke `load_gk_output` method there. These all use the correct run_directory if I'm not mistaken

E.g.
https://github.com/pyro-kinetics/pyrokinetics/blob/unstable/pyrokinetics/gs2.py#L545
https://github.com/pyro-kinetics/pyrokinetics/blob/unstable/pyrokinetics/cgyro.py#L526
https://github.com/pyro-kinetics/pyrokinetics/blob/unstable/pyrokinetics/gene.py#L494

**Comment by d7919** [comment]
Code looks to using it, but in practice this didn't seem to work for me. Will need to dig to find the exact failure mode.

**Comment by bpatel2107** [comment]
Is this still an issue?

**Comment by d7919** [comment]
I've not tried it for a while I'm afraid as I changed my workflow to avoid this. Happy for this to be closed.
