### ISSUE TITLE
Auto file detection not working

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#72]
When I try to auto-detect a file it fails here

https://github.com/pyro-kinetics/pyrokinetics/blob/6c59544c36a8f8140cede0d3a024fedecb096a00/pyrokinetics/pyro.py#L177

Where exactly does the inference take place. We need to implement that before we get to the `read_gk_file` method. @LiamPattinson do we need to add a check if `gk_file is not None` and `gk_code is None` to try and infer the file type when a pyro object is initialised?

**Comment by ZedThree** [comment]
Can you post the file that fails? Maybe replacing some of the values if they're sensitive

**Comment by bpatel2107** [comment]
It's just this


```python
from pyrokinetics import Pyro

# Point to CGYRO input file
gk_file = 'cgyro_input.txt'

# Load in file
pyro = Pyro(gk_file=gk_file)
```

[cgyro_input.txt](https://github.com/pyro-kinetics/pyrokinetics/files/8350782/cgyro_input.txt)

**Comment by LiamPattinson** [comment]
Apologies for that, it looks like I didn't push changes to the Pyro object. It certainly works with the refactored version I'm working on, but I'll put some effort into getting it working in a PR from the current unstable branch.
