### ISSUE TITLE
Fails to read and write CGYRO and GENE inputs

### ISSUE THREAD

**Issue by LiamPattinson** [bpatel2107/pyrokinetics#74]
```python
from pyrokinetics import Pyro, template_dir

pyro = Pyro(gk_file=template_dir / "input.gs2", gk_code="GS2")
pyro.write_gk_file("tmp")
# works fine

pyro = Pyro(gk_file=template_dir / "input.cgyro", gk_code="CGYRO")
pyro.write_gk_file("tmp")
# fails, as miller.B0 is None.
# This doesn't fail in the ongoing gk refactor PR.

pyro = Pyro(gk_file=template_dir / "input.gene", gk_code="GENE")
pyro.write_gk_file("tmp")
# fails, as miller does not have Rgeo set
```

It looks like in both failure cases, certain Miller attributes are unset. In the CGYRO case, `miller.B0 = None` when reading the template file, but we require it to be set when writing. This doesn't fail in the refactor PR https://github.com/pyro-kinetics/pyrokinetics/pull/67, as `miller.B0` is accessed only if `local_species.nref is not None` (which itself may be a bug). In the GENE case, we expect `miller.Rgeo` to exist when writing, but it is never set when reading.

**Comment by bpatel2107** [comment]
`miller.Rgeo` was removed as it was a redundant parameter, but we must have not changed it in the GENE file writer. I can remove that. 

`miller.B0` is proportional to `BETAE_UNIT` in the template file which is 0.0 so it gets set to `None`. This only happens in electrostatic simulations. In the writer, we try and find the reference magnetic field from `miller.B0` but we need to check if this is `None` before trying to calculate it.
