### ISSUE TITLE
underscore in mode_frequency/growth_rate xarray keys breaking plotting

### ISSUE THREAD

**Issue by bpatel2107** [bpatel2107/pyrokinetics#87]
The xarray keys for the mode frequency are growth rate are `mode_frequency` and `growth_rate` which will break matplotlib when writing labels as it will think it is a Latex expression.

@ZedThree  Shall I just change it to `mode-frequency` and `growth-rate`. Is there a good way to warn people about this?

**Comment by ZedThree** [comment]
Whereabouts is it breaking? Is it in pyrokinetics, or in like `df["mode_frequency"].plot()`?

**Comment by bpatel2107** [comment]
In `df["mode_frequency"].plot()`

I get an error like
![image](https://user-images.githubusercontent.com/15210802/174648217-89c7fe9e-a312-40ba-a1dc-ddb5e5538883.png)

**Comment by ZedThree** [comment]
Hmm, works for me. Do you have some custom matplotlib config maybe?

**Comment by bpatel2107** [comment]
I have set `text.use_tex: True` by default
