### ISSUE TITLE
gs2 code calculated frequency and growth rates to be included into pyro structure

### ISSUE THREAD

**Issue by whornsby82** [bpatel2107/pyrokinetics#94]
There are some cases when running gs2 that, due to selection of frequency of mode output frequencies, the Pyrokinetics and gs2 calculated linear mode frequencies don't agree.  Could the gs2 calculated values be included for the possibility of cross checking or using this other calculation?

**Comment by bpatel2107** [comment]
Might be worth adding a flag in `load_gk_output` that lets you choose where to get the data from. 

This is only an issue when the data isn't output at a high enough frequency and there are only a few time points.

**Comment by d7919** [comment]
It might also be an issue if the run hasn't reached full convergence as well (if I understand the issue correctly).

**Comment by bpatel2107** [comment]
Well this goes away in gs2 if you lower `nwrite` and `navg` in the diagnostics. 

Assuming the tolerance is set correctly then I don't think this will be an issue unless you are reading data partway through a simulation
