### ISSUE TITLE
Suggested code: GKW

### ISSUE THREAD

**Issue by d7919** [bpatel2107/pyrokinetics#96]
It would be useful to also support the GKW gyrokinetic code.

**Comment by bpatel2107** [comment]
I've not used GKW before. Do you think you can add it?

**Comment by whornsby82** [comment]
Hello guys, if you need help with gkw here, id be glad to help

**Comment by bpatel2107** [comment]
That's amazing! We would essentially need to copy/paste a `GKInput` and `GKOutputReader` from here https://github.com/pyro-kinetics/pyrokinetics/tree/unstable/pyrokinetics/gk_code

And just change the mappings from lets say GS2 to GKW inputs. Do we know which code it is most similar to in terms of input files structure and outputs?

**Comment by whornsby82** [comment]
Hmmm I don't have a huge amount of experience with other gyrokinetic codes other than gs2 now.  Input is fairly similar to gs2 but output (at least linearly) is very different.  Growth rates, frequencies, quasilinear fluxes and mode structures are output in ascii files.  One can output 3d fields in straight up binary files, so its not as sophisticated here as gs2.

**Comment by arkabokshi** [comment]
Have started implementation in branch [add_gkw](https://github.com/pyro-kinetics/pyrokinetics/commit/4417bab4f28970c165a2ff7c919dfc6bf4316497).

**Comment by bpatel2107** [comment]
Completed in #325
